version: "3.8"

services:
  postgres:
    image: postgres:15.6
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - internal-net
    restart: unless-stopped

  keycloak_web:
    build:
      context: ./keycloak
    image: login-ponorogo:24.0.3
    container_name: keycloak_web
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      #pringgo
      #      KC_PROXY: edge
      #      KC_COOKIE_SAMESITE: none
      #      KC_COOKIE_SECURE: true
      #end

      #19 juli 2025
      KC_COOKIE_DOMAIN: .ponorogo.go.id
      KC_PROXY: edge
      KC_COOKIE_SECURE: true
      #end

      KC_HOSTNAME: login.ponorogo.go.id
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: true

      # tambahan untuk mendukung Cloudfalre Flexible SSL
      # KC_PROXY: edge
      KC_HTTP_ENABLED: true
      KC_HTTP_RELATIVE_PATH: /

      KC_PROXY_HEADERS: xforwarded

      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    command: start-dev
    depends_on:
      - postgres
    ports:
      - 8080:8080
    networks:
      - internal-net
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  internal-net:
    driver: bridge
